import { Tenant, User, Product, Template, SubscriptionPlan, Campaign } from '../src/types';

export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan_free',
    name: 'Gratuito',
    priceMonthly: 0,
    artsLimitMonth: 10,
    hasWatermark: true,
    hasBulkGenerator: false,
    hasPdfFlyer: false,
    hasOnlineCatalog: true,
    hasTvMode: false,
    hasMultiStore: false,
  },
  {
    id: 'plan_basic',
    name: 'Básico',
    priceMonthly: 79.90,
    artsLimitMonth: 100,
    hasWatermark: false,
    hasBulkGenerator: false,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: false,
    hasMultiStore: false,
  },
  {
    id: 'plan_pro',
    name: 'Profissional',
    priceMonthly: 149.90,
    artsLimitMonth: 500,
    hasWatermark: false,
    hasBulkGenerator: true,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: true,
    hasMultiStore: false,
  },
  {
    id: 'plan_premium',
    name: 'Enterprise / Redes',
    priceMonthly: 299.90,
    artsLimitMonth: 9999,
    hasWatermark: false,
    hasBulkGenerator: true,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: true,
    hasMultiStore: true,
  }
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant_supermercado_modelo',
    name: 'Supermercado Modelo',
    slug: 'supermercado-modelo',
    status: 'ACTIVE',
    planId: 'plan_pro',
    createdAt: '2026-01-15T10:00:00.000Z',
    brandKit: {
      primaryColor: '#f43f5e',
      secondaryColor: '#facc15',
      accentColor: '#10b981',
      fontFamily: 'Outfit',
      instagram: '@supermercado_modelo',
      phone: '(11) 98765-4321',
      address: 'Av. Paulista, 1500 - São Paulo, SP',
      slogan: 'O menor preço da região todo dia!',
      customFooter: 'Ofertas válidas enquanto durarem os estoques. Fotos meramente ilustrativas.',
      logoUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=300&auto=format&fit=crop&q=80',
    }
  },
  {
    id: 'tenant_acougue_prime',
    name: 'Açougue & Boutique Prime',
    slug: 'acougue-prime',
    status: 'ACTIVE',
    planId: 'plan_pro',
    createdAt: '2026-02-01T10:00:00.000Z',
    brandKit: {
      primaryColor: '#dc2626',
      secondaryColor: '#f59e0b',
      accentColor: '#0f172a',
      fontFamily: 'Outfit',
      instagram: '@acougueprime_oficial',
      phone: '(11) 97777-8888',
      address: 'Rua das Carnes, 250 - São Paulo, SP',
      slogan: 'As melhores carnes nobres e kits churrasco',
      customFooter: 'Preços por KG. Carne fresca selecionada diariamente.',
      logoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=300&auto=format&fit=crop&q=80',
    }
  },
  {
    id: 'tenant_hortifruti_natura',
    name: 'Hortifruti Natura Fresca',
    slug: 'hortifruti-natura',
    status: 'ACTIVE',
    planId: 'plan_basic',
    createdAt: '2026-02-10T10:00:00.000Z',
    brandKit: {
      primaryColor: '#10b981',
      secondaryColor: '#fef08a',
      accentColor: '#d97706',
      fontFamily: 'Inter',
      instagram: '@hortifruti_natura',
      phone: '(11) 96666-5555',
      address: 'Praça das Flores, 88 - São Paulo, SP',
      slogan: 'Da horta direto para a sua mesa!',
      customFooter: 'Feira fresca todas as terças e quintas-feiras.',
      logoUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=300&auto=format&fit=crop&q=80',
    }
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_super_admin',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Carlos Mendes (Super Admin)',
    email: 'admin@promoja.com.br',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin_modelo',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Roberto Silva (Gerente Modelo)',
    email: 'gerente@supermercadomodelo.com.br',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_colaborador_modelo',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Mariana Costa (Marketing)',
    email: 'marketing@supermercadomodelo.com.br',
    role: 'COLABORADOR',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_101',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Cerveja Heineken Long Neck 330ml',
    brand: 'Heineken',
    categoryId: 'cat_bebidas',
    categoryName: 'Bebidas',
    code: '7891991000840',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500&auto=format&fit=crop&q=80',
    priceNormal: 7.49,
    pricePromotional: 5.49,
    unit: 'UN',
    isHighlight: true,
    highlightTag: 'SUPER OFERTA',
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_102',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Refrigerante Coca-Cola Original 2 Litros',
    brand: 'Coca-Cola',
    categoryId: 'cat_bebidas',
    categoryName: 'Bebidas',
    code: '7894900011517',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    priceNormal: 10.99,
    pricePromotional: 7.99,
    unit: 'UN',
    isHighlight: true,
    highlightTag: 'OFERTA DO DIA',
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_103',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Arroz Tipo 1 Tio João 5kg',
    brand: 'Tio João',
    categoryId: 'cat_mercearia',
    categoryName: 'Mercearia',
    code: '7896006700012',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    priceNormal: 34.90,
    pricePromotional: 26.90,
    unit: 'UN',
    weight: '5kg',
    isHighlight: true,
    highlightTag: 'MENOR PREÇO',
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_104',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Picanha Bovina Grill Maturada Friboi',
    brand: 'Friboi',
    categoryId: 'cat_carnes',
    categoryName: 'Açougue',
    code: '7891000112233',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=500&auto=format&fit=crop&q=80',
    priceNormal: 89.90,
    pricePromotional: 64.90,
    unit: 'KG',
    isHighlight: true,
    highlightTag: 'CHURRASCO',
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_105',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Café Torrado e Moído Pilão 500g',
    brand: 'Pilão',
    categoryId: 'cat_mercearia',
    categoryName: 'Mercearia',
    code: '7896001234567',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&auto=format&fit=crop&q=80',
    priceNormal: 19.90,
    pricePromotional: 14.90,
    unit: 'UN',
    weight: '500g',
    isHighlight: false,
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_107',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Banana Prata Selecionada',
    brand: 'Horta Fresca',
    categoryId: 'cat_hortifruti',
    categoryName: 'Hortifruti',
    code: '7891234000111',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80',
    priceNormal: 7.99,
    pricePromotional: 4.99,
    unit: 'KG',
    isHighlight: true,
    highlightTag: 'OFERTA IMPERDÍVEL',
    status: 'ACTIVE',
    createdAt: '2026-03-01T10:00:00.000Z',
  }
];

export const INITIAL_TEMPLATES: Template[] = [
  // STORIES 9:16 - SUPERMERCADO PREMIUM 3D
  {
    id: 'tpl_story_supermercado_vermelho',
    name: 'Super Varejo Impacto Red - Stories (9:16)',
    category: 'SUPERMERCADO',
    format: 'STORIES_9_16',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=300&auto=format&fit=crop&q=80',
    bgGradient: 'linear-gradient(135deg, #f43f5e 0%, #be123c 50%, #4c0519 100%)',
    hasSpotlight: true,
    spotlightColor: 'rgba(255, 255, 255, 0.4)',
    isGlobal: true,
    elements: [
      {
        id: 'el_ribbon',
        type: 'ribbon_banner',
        label: 'Faixa do Topo',
        posX: 60,
        posY: 100,
        width: 960,
        height: 140,
        bgColor: '#facc15',
        fontColor: '#0f172a',
        fontSize: 48,
        dynamicField: '{{tag_destaque}}',
        zIndex: 1,
      },
      {
        id: 'el_product_image',
        type: 'image',
        label: 'Imagem do Produto',
        posX: 140,
        posY: 300,
        width: 800,
        height: 720,
        dynamicField: '{{imagem_produto}}',
        zIndex: 2,
      },
      {
        id: 'el_starburst',
        type: 'starburst_badge',
        label: 'Selo Estrelado -% OFF',
        posX: 80,
        posY: 260,
        width: 260,
        height: 260,
        bgColor: '#10b981',
        fontColor: '#ffffff',
        fontSize: 52,
        dynamicField: '{{desconto_percentual}}',
        zIndex: 4,
      },
      {
        id: 'el_product_name',
        type: 'text',
        label: 'Nome do Produto',
        posX: 60,
        posY: 1060,
        width: 960,
        height: 120,
        fontSize: 58,
        fontColor: '#ffffff',
        fontFamily: 'Outfit',
        fontStyle: 'black',
        alignment: 'center',
        dynamicField: '{{nome_produto}}',
        zIndex: 5,
      },
      {
        id: 'el_price_normal',
        type: 'price_normal',
        label: 'Preço Antigo',
        posX: 100,
        posY: 1210,
        width: 880,
        height: 50,
        fontSize: 42,
        fontColor: '#cbd5e1',
        alignment: 'center',
        dynamicField: 'De {{preco_normal}}',
        zIndex: 6,
      },
      {
        id: 'el_price_promotional_box',
        type: 'shape',
        label: 'Caixa de Preço Destaque',
        posX: 100,
        posY: 1280,
        width: 880,
        height: 240,
        bgColor: '#facc15',
        borderRadius: 36,
        borderColor: '#ffffff',
        borderWidth: 6,
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 24,
        zIndex: 7,
      },
      {
        id: 'el_price_promotional',
        type: 'price_promotional',
        label: 'Preço Promocional',
        posX: 120,
        posY: 1335,
        width: 840,
        height: 140,
        fontSize: 115,
        fontColor: '#0f172a',
        fontFamily: 'Outfit',
        fontStyle: 'black',
        alignment: 'center',
        dynamicField: 'R$ {{preco_promocional}}',
        zIndex: 8,
      },
      {
        id: 'el_footer_brand',
        type: 'brand_info',
        label: 'Rodapé Comercial',
        posX: 60,
        posY: 1650,
        width: 960,
        height: 160,
        fontSize: 34,
        fontColor: '#ffffff',
        alignment: 'center',
        dynamicField: '{{nome_empresa}} • {{instagram_empresa}}',
        zIndex: 9,
      }
    ]
  },

  // FEED 1:1 - HORTIFRUTI VERDE FRESCO
  {
    id: 'tpl_feed_hortifruti_green',
    name: 'Feira Fresca Hortifruti - Feed (1:1)',
    category: 'HORTIFRUTI',
    format: 'FEED_1_1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=300&auto=format&fit=crop&q=80',
    bgGradient: 'linear-gradient(180deg, #10b981 0%, #047857 50%, #022c22 100%)',
    hasSpotlight: true,
    spotlightColor: 'rgba(254, 240, 138, 0.35)',
    isGlobal: true,
    elements: [
      {
        id: 'el_ribbon',
        type: 'ribbon_banner',
        label: 'Faixa Feira',
        posX: 40,
        posY: 40,
        width: 1000,
        height: 120,
        bgColor: '#fef08a',
        fontColor: '#064e3b',
        fontSize: 48,
        content: '🌱 FEIRA FRESCA DA SEMANA',
        zIndex: 1,
      },
      {
        id: 'el_feed_img',
        type: 'image',
        label: 'Foto do Produto',
        posX: 100,
        posY: 180,
        width: 880,
        height: 520,
        dynamicField: '{{imagem_produto}}',
        zIndex: 3,
      },
      {
        id: 'el_feed_name',
        type: 'text',
        label: 'Nome do Produto',
        posX: 40,
        posY: 730,
        width: 1000,
        height: 80,
        fontSize: 48,
        fontColor: '#ffffff',
        fontStyle: 'bold',
        alignment: 'center',
        dynamicField: '{{nome_produto}}',
        zIndex: 4,
      },
      {
        id: 'el_feed_price_box',
        type: 'shape',
        label: 'Caixa de Preço',
        posX: 180,
        posY: 830,
        width: 720,
        height: 160,
        bgColor: '#fef08a',
        borderRadius: 24,
        zIndex: 5,
      },
      {
        id: 'el_feed_price',
        type: 'price_promotional',
        label: 'Preço Destaque',
        posX: 200,
        posY: 865,
        width: 680,
        height: 90,
        fontSize: 88,
        fontColor: '#064e3b',
        fontStyle: 'black',
        alignment: 'center',
        dynamicField: 'R$ {{preco_promocional}} {{unidade}}',
        zIndex: 6,
      }
    ]
  },

  // TV 16:9 - SLIDE PREMIUM BROADCAST
  {
    id: 'tpl_tv_16_9_modern',
    name: 'Broadcast Store TV Slide (1920x1080)',
    category: 'GENERICO',
    format: 'TV_16_9',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=300&auto=format&fit=crop&q=80',
    bgGradient: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #090d16 100%)',
    hasSpotlight: true,
    spotlightColor: 'rgba(244, 63, 94, 0.4)',
    isGlobal: true,
    elements: [
      {
        id: 'el_tv_left_img',
        type: 'image',
        label: 'Imagem do Produto',
        posX: 100,
        posY: 140,
        width: 800,
        height: 800,
        dynamicField: '{{imagem_produto}}',
        zIndex: 1,
      },
      {
        id: 'el_tv_right_title',
        type: 'text',
        label: 'Tag de Oferta',
        posX: 960,
        posY: 180,
        width: 860,
        height: 60,
        fontSize: 48,
        fontColor: '#facc15',
        fontStyle: 'bold',
        alignment: 'left',
        dynamicField: '{{tag_destaque}}',
        zIndex: 2,
      },
      {
        id: 'el_tv_right_name',
        type: 'text',
        label: 'Nome do Produto',
        posX: 960,
        posY: 270,
        width: 860,
        height: 180,
        fontSize: 64,
        fontColor: '#ffffff',
        fontStyle: 'black',
        alignment: 'left',
        dynamicField: '{{nome_produto}}',
        zIndex: 3,
      },
      {
        id: 'el_tv_price_box',
        type: 'shape',
        label: 'Caixa de Preço TV',
        posX: 960,
        posY: 520,
        width: 800,
        height: 240,
        bgColor: '#f43f5e',
        borderRadius: 32,
        shadowColor: 'rgba(244, 63, 94, 0.5)',
        shadowBlur: 30,
        zIndex: 4,
      },
      {
        id: 'el_tv_price',
        type: 'price_promotional',
        label: 'Preço TV',
        posX: 980,
        posY: 570,
        width: 760,
        height: 140,
        fontSize: 125,
        fontColor: '#ffffff',
        fontStyle: 'black',
        alignment: 'center',
        dynamicField: 'R$ {{preco_promocional}}',
        zIndex: 5,
      }
    ]
  }
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_final_de_semana',
    tenantId: 'tenant_supermercado_modelo',
    name: 'OFERTAS DO FINAL DE SEMANA',
    slug: 'ofertas-do-final-de-semana',
    startDate: '2026-09-04',
    endDate: '2026-09-07',
    status: 'ACTIVE',
    productIds: ['prod_101', 'prod_102', 'prod_103', 'prod_104', 'prod_105', 'prod_107'],
    templateId: 'tpl_story_supermercado_vermelho',
    formats: ['STORIES_9_16', 'FEED_1_1', 'TV_16_9', 'FLYER_A4'],
    createdBy: 'user_admin_modelo',
    createdAt: '2026-09-01T14:00:00.000Z',
    viewCount: 1420,
  }
];
