import { Tenant, User, Product, Template, SubscriptionPlan, Campaign } from '../src/types';

export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan_free',
    name: 'Gratuito',
    priceMonthly: 0,
    artsLimitMonth: 10,
    hasWatermark: true,
    hasBulkGenerator: false,
    hasPdfFlyer: false,
    hasOnlineCatalog: true,
    hasTvMode: false,
    hasMultiStore: false,
  },
  {
    id: 'plan_basic',
    name: 'Básico',
    priceMonthly: 79.90,
    artsLimitMonth: 100,
    hasWatermark: false,
    hasBulkGenerator: false,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: false,
    hasMultiStore: false,
  },
  {
    id: 'plan_pro',
    name: 'Profissional',
    priceMonthly: 149.90,
    artsLimitMonth: 500,
    hasWatermark: false,
    hasBulkGenerator: true,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: true,
    hasMultiStore: false,
  },
  {
    id: 'plan_premium',
    name: 'Enterprise / Redes',
    priceMonthly: 299.90,
    artsLimitMonth: 9999,
    hasWatermark: false,
    hasBulkGenerator: true,
    hasPdfFlyer: true,
    hasOnlineCatalog: true,
    hasTvMode: true,
    hasMultiStore: true,
  }
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant_supermercado_modelo',
    name: 'Supermercado Modelo',
    slug: 'supermercado-modelo',
    status: 'ACTIVE',
    planId: 'plan_pro',
    createdAt: '2026-01-01T00:00:00.000Z',
    brandKit: {
      primaryColor: '#e11d48',
      secondaryColor: '#facc15',
      accentColor: '#16a34a',
      fontFamily: 'Outfit',
      phone: '(11) 99888-7766',
      instagram: '@supermercadomodelo',
      address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
      slogan: 'As melhores ofertas da cidade todos os dias!',
      customFooter: 'Ofertas válidas enquanto durarem os estoques.',
      logoUrl: '',
    }
  },
  {
    id: 'tenant_acougue_prime',
    name: 'Açougue & Boutique Prime',
    slug: 'acougue-prime',
    status: 'ACTIVE',
    planId: 'plan_premium',
    createdAt: '2026-01-15T00:00:00.000Z',
    brandKit: {
      primaryColor: '#991b1b',
      secondaryColor: '#f59e0b',
      accentColor: '#dc2626',
      fontFamily: 'Montserrat',
      phone: '(11) 97777-6655',
      instagram: '@acougueprime',
      address: 'Rua Oscar Freire, 500 - Jardins, São Paulo - SP',
      slogan: 'Cortes nobres e carnes selecionadas com qualidade garantida.',
      customFooter: 'Preços válidos para pagamento em PIX ou Cartão.',
      logoUrl: '',
    }
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_superadmin',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Carlos Mendes (Super Admin)',
    email: 'carlos@promoja.com.br',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin_modelo',
    tenantId: 'tenant_supermercado_modelo',
    name: 'Roberto Silva (Gerente)',
    email: 'roberto@supermercadomodelo.com.br',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin_prime',
    tenantId: 'tenant_acougue_prime',
    name: 'Fernando Carneiro (Proprietário)',
    email: 'fernando@acougueprime.com.br',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  }
];

// BANCO DE DADOS LIMPO DE PRODUÇÃO REAL (0 PRODUTOS MOCKADOS)
export const INITIAL_PRODUCTS: Product[] = [];

// BANCO DE DADOS LIMPO DE PRODUÇÃO REAL (0 CAMPANHAS MOCKADAS)
export const INITIAL_CAMPAIGNS: Campaign[] = [];

export const INITIAL_TEMPLATES: Template[] = [
  {
    id: 'tpl_story_supermercado_vermelho',
    name: 'Varejo Impacto Vermelho & Amarelo',
    category: 'SUPERMERCADO',
    format: 'STORIES_9_16',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=300&auto=format&fit=crop&q=80',
    bgGradient: 'linear-gradient(180deg, #be123c 0%, #881337 100%)',
    hasSpotlight: true,
    spotlightColor: 'rgba(255, 255, 255, 0.35)',
    isGlobal: true,
    elements: [
      {
        id: 'el_header_ribbon',
        type: 'ribbon_banner',
        label: 'Tarja Superior',
        posX: 140,
        posY: 120,
        width: 800,
        height: 110,
        bgColor: '#facc15',
        fontColor: '#0f172a',
        fontSize: 52,
        content: 'OFERTA IMPERDÍVEL',
        zIndex: 1,
      },
      {
        id: 'el_prod_img',
        type: 'image',
        label: 'Foto do Produto',
        posX: 140,
        posY: 320,
        width: 800,
        height: 800,
        zIndex: 2,
      },
      {
        id: 'el_starburst',
        type: 'starburst_badge',
        label: 'Selo de Desconto',
        posX: 740,
        posY: 280,
        width: 240,
        height: 240,
        bgColor: '#10b981',
        fontColor: '#ffffff',
        fontSize: 54,
        zIndex: 5,
      },
      {
        id: 'el_title',
        type: 'text',
        label: 'Nome do Produto',
        posX: 90,
        posY: 1180,
        width: 900,
        height: 180,
        dynamicField: '{{nome_produto}}',
        fontSize: 64,
        fontColor: '#ffffff',
        fontStyle: 'black',
        alignment: 'center',
        zIndex: 3,
      },
      {
        id: 'el_price_normal',
        type: 'price_normal',
        label: 'Preço De',
        posX: 240,
        posY: 1390,
        width: 600,
        height: 70,
        fontSize: 42,
        fontColor: '#cbd5e1',
        alignment: 'center',
        zIndex: 4,
      },
      {
        id: 'el_price_box',
        type: 'shape',
        label: 'Caixa de Destaque',
        posX: 190,
        posY: 1470,
        width: 700,
        height: 185,
        bgColor: '#10b981',
        borderRadius: 36,
        borderColor: '#ffffff',
        borderWidth: 6,
        shadowBlur: 20,
        shadowColor: 'rgba(0,0,0,0.5)',
        zIndex: 4,
      },
      {
        id: 'el_price_promo',
        type: 'price_promotional',
        label: 'Preço Por',
        posX: 210,
        posY: 1490,
        width: 660,
        height: 145,
        fontSize: 115,
        fontColor: '#ffffff',
        alignment: 'center',
        zIndex: 5,
      },
      {
        id: 'el_footer_brand',
        type: 'text',
        label: 'Rodapé com Marca',
        posX: 90,
        posY: 1770,
        width: 900,
        height: 80,
        dynamicField: '{{nome_empresa}} • {{telefone_empresa}}',
        fontSize: 32,
        fontColor: '#facc15',
        fontStyle: 'bold',
        alignment: 'center',
        zIndex: 3,
      }
    ]
  },
  {
    id: 'tpl_feed_supermercado_verde',
    name: 'Hortifruti & Feira Verde (1:1)',
    category: 'HORTIFRUTI',
    format: 'FEED_1_1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&auto=format&fit=crop&q=80',
    bgGradient: 'linear-gradient(135deg, #15803d 0%, #022c22 100%)',
    hasSpotlight: true,
    spotlightColor: 'rgba(255, 255, 255, 0.25)',
    isGlobal: true,
    elements: [
      {
        id: 'el_header_tag',
        type: 'ribbon_banner',
        label: 'Banner de Cabeçalho',
        posX: 140,
        posY: 60,
        width: 800,
        height: 90,
        bgColor: '#facc15',
        fontColor: '#0f172a',
        fontSize: 44,
        content: 'FEIRA FRESQUINHA',
        zIndex: 1,
      },
      {
        id: 'el_prod_img_feed',
        type: 'image',
        label: 'Foto do Produto',
        posX: 180,
        posY: 180,
        width: 720,
        height: 520,
        zIndex: 2,
      },
      {
        id: 'el_title_feed',
        type: 'text',
        label: 'Nome do Produto',
        posX: 60,
        posY: 730,
        width: 960,
        height: 120,
        dynamicField: '{{nome_produto}}',
        fontSize: 52,
        fontColor: '#ffffff',
        fontStyle: 'black',
        alignment: 'center',
        zIndex: 3,
      },
      {
        id: 'el_price_promo_feed',
        type: 'price_promotional',
        label: 'Preço Por',
        posX: 240,
        posY: 880,
        width: 600,
        height: 120,
        fontSize: 98,
        fontColor: '#facc15',
        alignment: 'center',
        zIndex: 4,
      }
    ]
  }
];
